### PR TITLE
Implemented scans and ground truth masks for datasets

### PR DESCRIPTION
**Pull request by bpmweel**
* schema now supports scans and ground truth masks
* schema now supports algorithms with metrics
* schema now supports the patients array in clusters
* added flask route to serve files from the data dir

### CODE REVIEW

**Comment by kretep** [comment]
I'm probably missing something regarding the fetching of the files:
My file is located at fedmix-viewer/backend/data/data_artificial/files/predicted_masks/head_1/0/0.png
In the manifest it is referred to as files/predicted_masks/head_1/0/0.png
The graphql result shows http://localhost:5000/files/data_artificial/files/predicted_masks/head_1/0/0.png
But fetching it from that url returns 404.

**Comment by kretep** [comment]
By the way, there are some flake8 errors on testing: 
___________________________________________ FLAKE8-check ___________________________________________
/Users/peter/repos/esc/fedmix/fedmix-viewer/backend/tests/test_schema.py:5:1: F401 'flask' imported but unused
/Users/peter/repos/esc/fedmix/fedmix-viewer/backend/tests/test_schema.py:101:80: E501 line too long (98 > 79 characters)
/Users/peter/repos/esc/fedmix/fedmix-viewer/backend/tests/test_schema.py:101:99: W292 no newline at end of file

**Comment by bpmweel** [comment]
> I'm probably missing something regarding the fetching of the files:
> My file is located at fedmix-viewer/backend/data/data_artificial/files/predicted_masks/head_1/0/0.png
> In the manifest it is referred to as files/predicted_masks/head_1/0/0.png
> The graphql result shows http://localhost:5000/files/data_artificial/files/predicted_masks/head_1/0/0.png
> But fetching it from that url returns 404.

This is strange, because that is exactly the same setup as I have and for me it works.

**Comment by kretep** [comment]
File fetching works if I use `datadir = os.path.join(os.getcwd(), datadir)` in send_file. So maybe for me the relative path is resolved differently?

**Comment by bpmweel** [comment]
> File fetching works if I use `datadir = os.path.join(os.getcwd(), datadir)` in send_file. So maybe for me the relative path is resolved differently?

This is what I also noticed with when testing with @pushpanjalip. I have updated the file lookup to use absolute paths based on the datastore location.

@kretep can you try again with the latest update?

**Comment by kretep** [comment]
Seems to work fine now!

**Pull request merged**
