### PR TITLE
Feature/image scans grid

### PR DESCRIPTION
**Pull request by pushpanjalip**
This PR:

- Adds ScansGrid with mocked-data to Algorithm Output View
- Sliders for dynamically changing CaseNo, SliceNo & Surface Dice values
- Responsive ScansGrid

**Make sure to add data-artificial folder into frontend/static/mocked-data to test the scans grid**

| | |
|:-------------------------:|:-------------------------:|
|Screenshot 2020-10-22 at 15 37 33|Screenshot 2020-10-22 at 15 37 47|

### CODE REVIEW

**Comment by kretep** [comment]
Just to double check; I didn't see this before, but this is probably just an error in the algorithm, right? I.e. not with drawing the contours.

image

**Comment by kretep** [comment]
@pushpanjalip and did you intend to keep OldScanCanvas.vue and old-researcher-view.vue? Maybe delete or rename otherwise?

**Comment by kretep** [comment]
Looks fine otherwise. (For anyone else looking at this: I had to put my manifest directly in mocked-data, so one level higher than data_artificial)

**Comment by pushpanjalip** [comment]
> Looks fine otherwise. (For anyone else looking at this: I had to put my manifest directly in mocked-data, so one level higher than data_artificial)

I will add this into comment(Note) as well

**Review by kretep — APPROVED** [review]

**Pull request merged**
